//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ghor_Sheba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_details
    {
        public int id { get; set; }
        public int booking_id { get; set; }
        public int service_id { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Service Service { get; set; }
    }
}
