//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.Booking_Details = new HashSet<Booking_Details>();
            this.Booking_Service = new HashSet<Booking_Service>();
        }
    
        public int id { get; set; }
        public int customer_id { get; set; }
        public Nullable<int> total_cost { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<Booking_Details> Booking_Details { get; set; }
        public virtual ICollection<Booking_Service> Booking_Service { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
