//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public Coupon()
        {
            this.Customer_Coupon = new HashSet<Customer_Coupon>();
        }
    
        public int id { get; set; }
        public string status { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> min_order_amount { get; set; }
        public Nullable<int> max_use_number { get; set; }
    
        public virtual ICollection<Customer_Coupon> Customer_Coupon { get; set; }
    }
}
