//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider_Bonus
    {
        public int id { get; set; }
        public int service_provider_id { get; set; }
        public int bonus_id { get; set; }
    
        public virtual Bonu Bonu { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
    }
}
