//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider
    {
        public ServiceProvider()
        {
            this.Booking_Service = new HashSet<Booking_Service>();
            this.Reviews = new HashSet<Review>();
            this.ServiceProvider_Bonus = new HashSet<ServiceProvider_Bonus>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public string phone { get; set; }
        public string work_status { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> rating_count { get; set; }
        public Nullable<int> services_done { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<Booking_Service> Booking_Service { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<ServiceProvider_Bonus> ServiceProvider_Bonus { get; set; }
        public virtual User User { get; set; }
    }
}
