//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Customers = new HashSet<Customer>();
            this.Login_Time = new HashSet<Login_Time>();
            this.ProfilePictures = new HashSet<ProfilePicture>();
            this.Salaries = new HashSet<Salary>();
            this.ServiceProviders = new HashSet<ServiceProvider>();
            this.Tokens = new HashSet<Token>();
        }
    
        public int id { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string usertype { get; set; }
        public string verification_status { get; set; }
        public string id_status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Login_Time> Login_Time { get; set; }
        public virtual ICollection<ProfilePicture> ProfilePictures { get; set; }
        public virtual ICollection<Salary> Salaries { get; set; }
        public virtual ICollection<ServiceProvider> ServiceProviders { get; set; }
        public virtual ICollection<Token> Tokens { get; set; }
    }
}
