//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int id { get; set; }
        public int category_id { get; set; }
        public string news_title { get; set; }
        public string date_posted { get; set; }
        public string date_updated { get; set; }
        public string comment_status { get; set; }
        public int author_id { get; set; }
        public string status { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual News_category News_category { get; set; }
    }
}
