//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.order_details = new HashSet<order_details>();
        }
    
        public int Id { get; set; }
        public int Customer_id { get; set; }
        public string Status { get; set; }
        public int Price { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ICollection<order_details> order_details { get; set; }
    }
}
