//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.orders = new HashSet<order>();
        }
    
        public string Phone { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<order> orders { get; set; }
    }
}
