//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_users
    {
        public Login_users()
        {
            this.Bookings = new HashSet<Booking>();
            this.Complaints = new HashSet<Complaint>();
            this.Reviews = new HashSet<Review>();
            this.Service_provider_status = new HashSet<Service_provider_status>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string status { get; set; }
        public string user_type { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Complaint> Complaints { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<Service_provider_status> Service_provider_status { get; set; }
    }
}
